spring.application.name=SistemaDeVerificacion
server.port=${PORT:8080}
server.address=0.0.0.0
token.secret=${JWT_SECRET:1234}
token.expiration.hours=${JWT_EXPIRATION_HOURS:2}
qr.token.secret=${QR_SECRET:1234}
qr.token.expiration.minutes=5
#BASE DE DATOS
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/proyecto_seguridad}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:42664539}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


#ESTATICOS
spring.web.resources.static-locations=file:/home/matias/pruebas/**
spring.mvc.static-path-pattern=/images/** , /spreadsheets/**

#EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=${MAIL_USER:aguilardev29@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tpevkpqhfhiekmpb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

#MERCADOPAGO
mercadopago.access.token=${MERCADOPAGO_ACCESS_TOKEN:APP_USR-1757687960936668-091220-35458bb62399ff3b5acd46b55d0bdac0-2684382813}
mercadopago.sponsor.id=${MERCADOPAGO_SPONSOR_ID:318880079}

mercadopago.back.success.url=${APP_BASE_URL:https://248b9bfe35dc.ngrok-free.app}/v1/mercadopago/success
mercadopago.back.pending.url=${APP_BASE_URL:https://248b9bfe35dc.ngrok-free.app}/v1/mercadopago/pending
mercadopago.back.failure.url=${APP_BASE_URL:https://248b9bfe35dc.ngrok-free.app}/v1/mercadopago/failure
mercadopago.auto.return=approved
mercadopago.notification.path=/v1/mercadopago/notifications

#SUPABASE
supabase.url=${SUPABASE_URL:https://cbjedixtdbggtdiayfhx.supabase.co}
supabase.key=${SUPABASE_KEY:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiamVkaXh0ZGJnZ3RkaWF5Zmh4Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Nzk0ODM2NCwiZXhwIjoyMDczNTI0MzY0fQ.hgbd7Hb45dIGVZUb2nBtLEUbMTd0MMxG76xju3ZSijc}
supabase.bucket=files
